### PR TITLE
Google analytics 4 (GA4): configure CNCF ID

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to CNCF service desk request [Google Analytics setup for the Logging Operator documentation site CNCFSD-2325](https://cncfservicedesk.atlassian.net/browse/CNCFSD-2325)

/cc @nate-double-u

### CODE REVIEW

**Comment by fekete-robert** [comment]
Hi @chalin, many thanks for your help! I usually add the google id only to the production config, to avoid counting local builds, but that's probably not a big issue.

**Review by fekete-robert — APPROVED** [review]

**Comment by fekete-robert** [comment]
BTW, do you have a suggested way to show a cookie-consent banner (required because of Google Analytics), or each CNCF project uses its own solution?

**Comment by chalin** [comment]
> Hi @chalin, many thanks for your help! 

Hi @fekete-robert! Fancy meeting you here 😄 

> I usually add the google id only to the production config, to avoid counting local builds, but that's probably not a big issue.

Right, GA should only be enabled in production. If you were deploying to Netlify (which might be something you can ask for, cc @nate-double-u to be sure), then we could easily set up GA for production-only deploys via snippet injection.

But, as you probably know, Docsy will only enable GA in a production build, so if your site build is setup properly, all should be good.

**Comment by chalin** [comment]
> BTW, do you have a suggested way to show a cookie-consent banner (required because of Google Analytics), or each CNCF project uses its own solution?

I've been working towards a common solution that CNCF projects could adopt. This is still WIP / under investigation. If you feel that this is critical for your project, let me know and I'll see if I can bump up the priority a bit.

**Comment by fekete-robert** [comment]
> But, as you probably know, Docsy will only enable GA in a production build, so if your site build is setup properly, all should be good.

Oh, right, I forgot about that :)

**Comment by fekete-robert** [comment]
> I've been working towards a common solution that CNCF projects could adopt. This is still WIP / under investigation. If you feel that this is critical for your project, let me know and I'll see if I can bump up the priority a bit.

No need to rush, I think I have a standalone solution somewhere, I'll add that to the site and change it to the common CNCF solution when it's available.

**Comment by chalin** [comment]
I confirm that data is being received:

> image

**Comment by fekete-robert** [comment]
\o/
Many thanks for the help!

**Comment by chalin** [comment]
FYI: @nate-double-u and I were discussing that after the domain transfer is complete, we'd encourage a migration to Netlify.

**Comment by nate-double-u** [comment]
I've opened a new CNCF Service Desk ticket ([CNCFSD-2329](https://cncfservicedesk.atlassian.net/browse/CNCFSD-2329)) to help us track the domain transfer work.

**Comment by fekete-robert** [comment]
> FYI: @nate-double-u and I were discussing that after the domain transfer is complete, we'd encourage a migration to Netlify.

Sure, we can do that

**Pull request merged**
